
install:
	python3 -m pip install --upgrade pip
	python3 -m pip --no-cache-dir -r requirements.txt
	ls -al -R

run:
	export PYTHONUNBUFFERED=1
	export PYTHONDONTWRITEBYTECODE=1
	clear
	cat src/main.py
	python3 -m src.main